export const SERVICES_LIST_REQUEST = 'SERVICES_LIST_REQUEST';
export const SERVICES_LIST_SUCCESS = 'SERVICES_LIST_SUCCESS';

export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS';

export const SERVICES_FAILURE = 'SERVICES_FAILURE';